### ISSUE TITLE
Cannot send any sugar to any address

### ISSUE THREAD

**Issue by suerteahypapa** [Nugetzrul3/Sugarchain-Chrome-Wallet#14]
Everytime I keep trying to send sugar it keeps failing for some reason 66: min relay fee not met please check when you can so other users dont run in same problems

**Comment by Nugetzrul3** [comment]
Please make sure you have updated to the latest version on the chrome webstore:
https://chrome.google.com/webstore/detail/sugarchain-wallet-extensi/pgojdfajgcjjpjnbpfaelnpnjocakldb

Also, this error means that you have set the fee too low. Set a higher fee.

**Comment by suerteahypapa** [comment]
Thank you for replying i have have put more in fee 0.000010001 0.00001150 and still nothing it keeps saying error 66 cannot broadcast so its not the fee its something else im trying to send to AltMarkets
