### ISSUE TITLE
No save

### ISSUE THREAD

**Issue by joeland1** [Nugetzrul3/Sugarchain-Chrome-Wallet#2]
recommend some save, like session or something
all data lost except address when close and reopen extension.
should fix or maybe have remove button
idk, annoying to save imo

**Comment by Nugetzrul3** [comment]
Actually, wif key is saved but not displayed again for security purposes. In terms of saving session, I will work on it today :+1:

**Comment by Nugetzrul3** [comment]
Save session added: https://github.com/Nugetzrul3/Sugarchain-Chrome-Wallet/commit/20c86345a6c61089ebca09c6d86ddd3e1307e2d0
